apiVersion: v2
name: backend-api
description: Rentguard backend API service
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/jhav1643/rentguard/main/docs/logo.svg
