# infra/helm/ingestion/values-prod.yaml
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

envSecretName: rentguard-env

env:
  LOG_LEVEL: info
  PYTHONUNBUFFERED: "1"
  ENVIRONMENT: prod

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

serviceAccount:
  create: true
  name: ingestion
  annotations: {}

persistence:
  enabled: false
  claimName: rentguard-shared-data
  mounts: []
